contact_links:
  - name: Предложение
    url: https://dsc.gg/deadspace14
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://dsc.gg/deadspace14
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности ghost049#3771 (784795496622718986) в Discord.
